version: '3.3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  development:
    command: /bin/sh -c "while sleep 1000; do :; done"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/home/vscode
      
    env_file:
      - .devcontainer.env

    ports:
      - '2222:22'

volumes:
  debug:
    driver: local
      